import time

blacklist = [13734, 28733, 21697]

NEXT_DAY = int(time.time() + 60*60*22)

content_v6 = {
    "definitions": [],
    "probes": [],
    "is_oneoff": False,
    "stop_time": str(NEXT_DAY)
}

probe_dict = {
   "value": '',
   "type": "probes",
   "requested": 1
  }

definition_dict = {
   "target": '',
   "af": 6,
   "timeout": 4000,
   "description": "prueba 2",
   "protocol": "ICMP",
   "interval": 86400,
   "resolve_on_probe": False,
   "packets": 10,
   "size": 48,
   "first_hop": 1,
   "max_hops": 32,
   "paris": 16,
   "destination_option_size": 0,
   "hop_by_hop_option_size": 0,
   "dont_fragment": False,
   "skip_dns_check": True,
   "type": "traceroute"
  }


cc_to_rir = {
   u'AD': u'RIPE NCC',
   u'AE': u'RIPE NCC',
   u'AF': u'APNIC',
   u'AG': u'ARIN',
   u'AI': u'ARIN',
   u'AL': u'RIPE NCC',
   u'AM': u'RIPE NCC',
   u'AN': u'LACNIC',
   u'AO': u'AFRINIC',
   u'AQ': u'ARIN',
   u'AR': u'LACNIC',
   u'AS': u'APNIC',
   u'AT': u'RIPE NCC',
   u'AU': u'APNIC',
   u'AW': u'LACNIC',
   u'AX': u'RIPE NCC',
   u'AZ': u'RIPE NCC',
   u'BA': u'RIPE NCC',
   u'BB': u'ARIN',
   u'BD': u'APNIC',
   u'BE': u'RIPE NCC',
   u'BF': u'AFRINIC',
   u'BG': u'RIPE NCC',
   u'BH': u'RIPE NCC',
   u'BI': u'AFRINIC',
   u'BJ': u'AFRINIC',
   u'BM': u'ARIN',
   u'BN': u'APNIC',
   u'BO': u'LACNIC',
   u'BR': u'LACNIC',
   u'BS': u'ARIN',
   u'BT': u'APNIC',
   u'BV': u'ARIN',
   u'BW': u'AFRINIC',
   u'BY': u'RIPE NCC',
   u'BZ': u'LACNIC',
   u'CA': u'ARIN',
   u'CC': u'APNIC',
   u'CD': u'AFRINIC',
   u'CF': u'AFRINIC',
   u'CG': u'AFRINIC',
   u'CH': u'RIPE NCC',
   u'CI': u'AFRINIC',
   u'CK': u'APNIC',
   u'CL': u'LACNIC',
   u'CM': u'AFRINIC',
   u'CN': u'APNIC',
   u'CO': u'LACNIC',
   u'CR': u'LACNIC',
   u'CS': u'RIPE NCC',
   u'CU': u'LACNIC',
   u'CV': u'AFRINIC',
   u'CX': u'APNIC',
   u'CY': u'RIPE NCC',
   u'CZ': u'RIPE NCC',
   u'DE': u'RIPE NCC',
   u'DJ': u'AFRINIC',
   u'DK': u'RIPE NCC',
   u'DM': u'ARIN',
   u'DO': u'LACNIC',
   u'DZ': u'AFRINIC',
   u'EC': u'LACNIC',
   u'EE': u'RIPE NCC',
   u'EG': u'AFRINIC',
   u'EH': u'AFRINIC',
   u'ER': u'AFRINIC',
   u'ES': u'RIPE NCC',
   u'ET': u'AFRINIC',
   u'FI': u'RIPE NCC',
   u'FJ': u'APNIC',
   u'FK': u'LACNIC',
   u'FM': u'APNIC',
   u'FO': u'RIPE NCC',
   u'FR': u'RIPE NCC',
   u'GA': u'AFRINIC',
   u'GB': u'RIPE NCC',
   u'GD': u'ARIN',
   u'GE': u'RIPE NCC',
   u'GF': u'LACNIC',
   u'GH': u'AFRINIC',
   u'GI': u'RIPE NCC',
   u'GL': u'RIPE NCC',
   u'GM': u'AFRINIC',
   u'GN': u'AFRINIC',
   u'GP': u'ARIN',
   u'GQ': u'AFRINIC',
   u'GR': u'RIPE NCC',
   u'GS': u'LACNIC',
   u'GT': u'LACNIC',
   u'GU': u'APNIC',
   u'GW': u'AFRINIC',
   u'GY': u'LACNIC',
   u'HK': u'APNIC',
   u'HM': u'ARIN',
   u'HN': u'LACNIC',
   u'HR': u'RIPE NCC',
   u'HT': u'LACNIC',
   u'HU': u'RIPE NCC',
   u'ID': u'APNIC',
   u'IE': u'RIPE NCC',
   u'IL': u'RIPE NCC',
   u'IN': u'APNIC',
   u'IO': u'APNIC',
   u'IQ': u'RIPE NCC',
   u'IR': u'RIPE NCC',
   u'IS': u'RIPE NCC',
   u'IT': u'RIPE NCC',
   u'JM': u'ARIN',
   u'JO': u'RIPE NCC',
   u'JP': u'APNIC',
   u'KE': u'AFRINIC',
   u'KG': u'RIPE NCC',
   u'KH': u'APNIC',
   u'KI': u'APNIC',
   u'KM': u'AFRINIC',
   u'KN': u'ARIN',
   u'KP': u'APNIC',
   u'KR': u'APNIC',
   u'KW': u'RIPE NCC',
   u'KY': u'ARIN',
   u'KZ': u'RIPE NCC',
   u'LA': u'APNIC',
   u'LB': u'RIPE NCC',
   u'LC': u'ARIN',
   u'LI': u'RIPE NCC',
   u'LK': u'APNIC',
   u'LR': u'AFRINIC',
   u'LS': u'AFRINIC',
   u'LT': u'RIPE NCC',
   u'LU': u'RIPE NCC',
   u'LV': u'RIPE NCC',
   u'LY': u'AFRINIC',
   u'MA': u'AFRINIC',
   u'MC': u'RIPE NCC',
   u'MD': u'RIPE NCC',
   u'MG': u'AFRINIC',
   u'MH': u'APNIC',
   u'MK': u'RIPE NCC',
   u'ML': u'AFRINIC',
   u'MM': u'APNIC',
   u'MN': u'APNIC',
   u'MO': u'APNIC',
   u'MP': u'APNIC',
   u'MQ': u'ARIN',
   u'MR': u'AFRINIC',
   u'MS': u'RIPE NCC',
   u'MT': u'RIPE NCC',
   u'MU': u'AFRINIC',
   u'MV': u'APNIC',
   u'MW': u'ARIN',
   u'MX': u'LACNIC',
   u'MY': u'APNIC',
   u'MZ': u'AFRINIC',
   u'NC': u'APNIC',
   u'NE': u'AFRINIC',
   u'NF': u'APNIC',
   u'NG': u'AFRINIC',
   u'NI': u'LACNIC',
   u'NL': u'RIPE NCC',
   u'NO': u'RIPE NCC',
   u'NP': u'APNIC',
   u'NR': u'APNIC',
   u'NU': u'APNIC',
   u'NZ': u'APNIC',
   u'OM': u'RIPE NCC',
   u'PA': u'LACNIC',
   u'PE': u'LACNIC',
   u'PF': u'APNIC',
   u'PG': u'APNIC',
   u'PH': u'APNIC',
   u'PK': u'APNIC',
   u'PL': u'RIPE NCC',
   u'PM': u'ARIN',
   u'PN': u'APNIC',
   u'PR': u'ARIN',
   u'PS': u'RIPE NCC',
   u'PT': u'RIPE NCC',
   u'PW': u'APNIC',
   u'PY': u'LACNIC',
   u'QA': u'RIPE NCC',
   u'RE': u'AFRINIC',
   u'RO': u'RIPE NCC',
   u'RU': u'RIPE NCC',
   u'RW': u'AFRINIC',
   u'SA': u'RIPE NCC',
   u'SB': u'APNIC',
   u'SC': u'AFRINIC',
   u'SD': u'AFRINIC',
   u'SE': u'RIPE NCC',
   u'SG': u'APNIC',
   u'SH': u'ARIN',
   u'SI': u'RIPE NCC',
   u'SJ': u'RIPE NCC',
   u'SK': u'RIPE NCC',
   u'SL': u'AFRINIC',
   u'SM': u'RIPE NCC',
   u'SN': u'AFRINIC',
   u'SO': u'AFRINIC',
   u'SR': u'LACNIC',
   u'ST': u'AFRINIC',
   u'SV': u'LACNIC',
   u'SY': u'RIPE NCC',
   u'SZ': u'AFRINIC',
   u'TC': u'ARIN',
   u'TD': u'AFRINIC',
   u'TF': u'APNIC',
   u'TG': u'AFRINIC',
   u'TH': u'APNIC',
   u'TJ': u'RIPE NCC',
   u'TK': u'APNIC',
   u'TL': u'APNIC',
   u'TM': u'RIPE NCC',
   u'TN': u'AFRINIC',
   u'TO': u'APNIC',
   u'TR': u'RIPE NCC',
   u'TT': u'LACNIC',
   u'TV': u'APNIC',
   u'TW': u'APNIC',
   u'TZ': u'AFRINIC',
   u'UA': u'RIPE NCC',
   u'UG': u'AFRINIC',
   u'UM': u'ARIN',
   u'US': u'ARIN',
   u'UY': u'LACNIC',
   u'UZ': u'RIPE NCC',
   u'VA': u'RIPE NCC',
   u'VC': u'ARIN',
   u'VE': u'LACNIC',
   u'VG': u'ARIN',
   u'VI': u'ARIN',
   u'VN': u'APNIC',
   u'VU': u'APNIC',
   u'WF': u'APNIC',
   u'WS': u'APNIC',
   u'YE': u'RIPE NCC',
   u'YT': u'APNIC',
   u'ZA': u'AFRINIC',
   u'ZM': u'AFRINIC',
   u'ZW': u'AFRINIC'}
